Repository eventespresso/eea-wait-lists, pull requests merged in 2019-04, with the labels that each got.

#13 Just redirect to the referring url
  domain/services/modules/EED_Wait_Lists.module.php
Labels: status:needs-testing, type:bug 🐞

#16 Fix fatals on test sends of message types including recipient link (fixes #15)
  domain/services/modules/EED_Wait_Lists.module.php
Labels: category:messaging-&-messengers, type:bug 🐞

#17 Set the user_id (which is the event author id) on the EE_Messages_Addressee
  domain/entities/EE_Waitlist_Message_Type_Base.class.php
Labels: category:messaging-&-messengers, type:enhancement 🎉

#14 Remove Google Plus from default templates
  views/messages/templates/email_registration_added_to_waitlist_content.template.php
  views/messages/templates/email_registration_demoted_to_waitlist_content.template.php
  views/messages/templates/email_waitlist_can_register_content.template.php
Labels: category:messaging-&-messengers, status:needs-testing
